---
driver:
  name: azurerm

driver_config:
  #subscription_id: 'b02e675a-cee0-49bd-a056-daa7ed05bf4e'
  subscription_id: <%= ENV['AZURE_SUBSCRIPTION'] %>
  location: 'East US'
  machine_size: 'Standard_A2_v2'

provisioner:
  name: chef_zero
  sudo: true


#platforms:
#  - name: linux
#    driver_config:
#      image_urn: Canonical:UbuntuServer:14.04.4-LTS:latest

transport:
  #ssh_key: '~/.ssh/rlupo_azure_key'
  ssh_key: <%= ENV['AZURE_KEY'] %>

platforms:
  - name: centos
    driver_config:
      image_urn: OpenLogic:CentOS:7.2:latest

suites:
  <%  1.upto(2) do |n| %>
  - name: hab-ws-nyc-<%= n %>
    run_list:
      - recipe[habitat_azure_workstation]
    driver:
      vm_name: hab-ws-nyc-<%= n %>
    attributes:
  <% end %>
