---
driver:
  name: azurerm

driver_config:
  subscription_id: <%= ENV['AZURE_SUBSCRIPTION'] %>
  location: 'East US'
  machine_size: 'Standard_A2_v2'
  azure_resource_group_name: habitat-rg

provisioner:
  name: chef_zero
  sudo: true

transport:
  ssh_key: <%= ENV['AZURE_KEY'] %>

platforms:
  - name: centos
    driver_config:
      image_urn: OpenLogic:CentOS:7.2:latest

suites:
  <%  1.upto(2) do |n| %>
  - name: hab-ws-nyc-<%= n %>
    run_list:
      - recipe[habitat_azure_workstation]
    driver:
      vm_name: hab-ws-nyc-<%= n %>
    attributes:
  <% end %>
